"""references table

Revision ID: 33596c423a0e
Revises: 240d6e765e57
Create Date: 2026-05-06 09:55:15.200286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33596c423a0e'
down_revision: Union[str, Sequence[str], None] = '240d6e765e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_listing_id', sa.String(length=50), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('original_images_json', sa.Text(), nullable=False),
    sa.Column('ai_title_variants_json', sa.Text(), nullable=True),
    sa.Column('edited_title', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.String(length=500), nullable=True),
    sa.Column('kept_image_indices_json', sa.String(length=200), nullable=True),
    sa.Column('cutout_design_id', sa.Integer(), nullable=True),
    sa.Column('notion_page_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cutout_design_id'], ['designs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('references')
    # ### end Alembic commands ###
