"""add_artworks_table

Revision ID: 81fe2ec1dc2b
Revises: 36665e3c284b
Create Date: 2026-05-20 14:25:01.970532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fe2ec1dc2b'
down_revision: Union[str, Sequence[str], None] = '36665e3c284b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('original_url', sa.String(length=500), nullable=True),
    sa.Column('cropped_url', sa.String(length=500), nullable=True),
    sa.Column('refined_url', sa.String(length=500), nullable=True),
    sa.Column('removebg_url', sa.String(length=500), nullable=True),
    sa.Column('final_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artworks')
    # ### end Alembic commands ###
