"""idea_schema_v08

Revision ID: d17139d27fbb
Revises: 415233eecbd4
Create Date: 2026-05-07 15:21:09.517842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17139d27fbb'
down_revision: Union[str, Sequence[str], None] = '415233eecbd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_listing_id', sa.String(length=64), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('materials_json', sa.Text(), nullable=True),
    sa.Column('taxonomy_id', sa.Integer(), nullable=True),
    sa.Column('who_made', sa.String(length=50), nullable=True),
    sa.Column('when_made', sa.String(length=50), nullable=True),
    sa.Column('reference_image_url', sa.String(length=2000), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_listing_id', name='uq_ideas_source_pair')
    )
    op.create_index('idx_ideas_keyword', 'ideas', ['keyword_id'], unique=False)
    op.create_index('idx_ideas_status', 'ideas', ['status'], unique=False)
    op.create_table('idea_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('num_favorers', sa.Integer(), nullable=True),
    sa.Column('views_all_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_idea_ts', 'idea_signals', ['idea_id', 'ts'], unique=False)
    op.create_table('idea_to_listing',
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idea_id', 'listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idea_to_listing')
    op.drop_index('idx_signals_idea_ts', table_name='idea_signals')
    op.drop_table('idea_signals')
    op.drop_index('idx_ideas_status', table_name='ideas')
    op.drop_index('idx_ideas_keyword', table_name='ideas')
    op.drop_table('ideas')
    op.drop_table('keywords')
    # ### end Alembic commands ###
