"""add_notion_page_id_and_final_image_url

Revision ID: e7d4a402ca7b
Revises: 0001
Create Date: 2026-05-05 09:43:00.014180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d4a402ca7b'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('notion_page_id', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_listings_etsy_listing_id'), table_name='listings')
    op.create_index(op.f('ix_listings_etsy_listing_id'), 'listings', ['etsy_listing_id'], unique=True)
    op.add_column('mockup_variants', sa.Column('final_image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mockup_variants', 'final_image_url')
    op.drop_index(op.f('ix_listings_etsy_listing_id'), table_name='listings')
    op.create_index(op.f('ix_listings_etsy_listing_id'), 'listings', ['etsy_listing_id'], unique=False)
    op.drop_column('listings', 'notion_page_id')
    # ### end Alembic commands ###
